apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::284808363569:role/UdacityFlaskDeployCBKubectlRole
      username: build 
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::284808363569:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1K41WA6AL3N8Z
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-09T23:49:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1977"
  uid: 44843f26-55cb-4803-9dc4-06d50a679a96
